// SPDX-License-Identifier: Hippocratic-3.0
import type { FastifyInstance } from 'fastify';
import fp from 'fastify-plugin';
import { sql } from 'drizzle-orm';
import { readFileSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import '../types.ts';
import { uiTranslations } from '../db/schema/ui-translations.ts';

/**
 * Boot-time UI translations seeder.
 *
 * Reads packages/server/src/db/seed-data/ui-translations.json (committed
 * to the repo) and upserts every (lang, key, value) row into the
 * ui_translations table on app start. The unique index on (lang, key)
 * makes this idempotent — fresh deployments get the full set, and
 * existing deployments pick up new or updated strings the next time
 * they boot.
 *
 * The JSON file is regenerated by `npm run dump:i18n` after running
 * `seed:i18n` against a dev database. See those scripts for details.
 */

const CHUNK_SIZE = 100;

async function i18nSeedPlugin(fastify: FastifyInstance) {
  fastify.addHook('onReady', async () => {
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = dirname(__filename);
    // From plugins/ → ../db/seed-data/ui-translations.json
    const seedPath = `${__dirname}/../db/seed-data/ui-translations.json`;

    if (!existsSync(seedPath)) {
      fastify.log.info(
        { seedPath },
        'i18n seed file not found; skipping UI translation upsert',
      );
      return;
    }

    let data: Record<string, Record<string, string>>;
    try {
      const raw = readFileSync(seedPath, 'utf-8');
      data = JSON.parse(raw);
    } catch (err) {
      fastify.log.error({ err, seedPath }, 'Failed to read i18n seed file');
      return;
    }

    const rows: { lang: string; key: string; value: string }[] = [];
    for (const lang of Object.keys(data)) {
      for (const key of Object.keys(data[lang])) {
        rows.push({ lang, key, value: data[lang][key] });
      }
    }

    if (rows.length === 0) {
      fastify.log.info('i18n seed file is empty; nothing to upsert');
      return;
    }

    let upserted = 0;
    for (let i = 0; i < rows.length; i += CHUNK_SIZE) {
      const chunk = rows.slice(i, i + CHUNK_SIZE);
      await fastify.db
        .insert(uiTranslations)
        .values(chunk)
        .onConflictDoUpdate({
          target: [uiTranslations.lang, uiTranslations.key],
          set: {
            value: sql`excluded.value`,
            updatedAt: sql`now()`,
          },
        });
      upserted += chunk.length;
    }

    fastify.log.info(
      { count: upserted, languages: Object.keys(data).length },
      'UI translations seeded from JSON',
    );
  });
}

export default fp(i18nSeedPlugin, {
  name: 'i18n-seed',
  dependencies: ['db'],
});
